// This GUI file is generated by guibuilder version 4.2.2
//////////
f=figure('figure_position',[-8,-8],'figure_size',[1479,930],'auto_resize','on','background',[34],'figure_name','Graphic window number %d','color_map',[0,0,0;0,0,1;0,1,0;0,1,1;1,0,0;1,0,1;1,1,0;1,1,1;0,0,0.5647059;0,0,0.6901961;0,0,0.8156863;0.5294118,0.8078431,1;0,0.5647059,0;0,0.6901961,0;0,0.8156863,0;0,0.5647059,0.5647059;0,0.6901961,0.6901961;0,0.8156863,0.8156863;0.5647059,0,0;0.6901961,0,0;0.8156863,0,0;0.5647059,0,0.5647059;0.6901961,0,0.6901961;0.8156863,0,0.8156863;0.5019608,0.1882353,0;0.627451,0.2509804,0;0.7529412,0.3764706,0;1,0.5019608,0.5019608;1,0.627451,0.627451;1,0.7529412,0.7529412;1,0.8784314,0.8784314;1,0.8431373,0;0.8,0.8,0.8;0.9333333,0.9333333,0.9333333],'dockable','off','infobar_visible','off','toolbar_visible','off','menubar_visible','off','default_axes','on','visible','off');
//////////
handles.dummy = 0;
handles.mainFigure=uicontrol(f,'unit','normalized','BackgroundColor',[0.96,0.96,0.96],'Enable','on','FontAngle','normal','FontName','Tahoma','FontSize',[12],'FontUnits','points','FontWeight','normal','ForegroundColor',[-1,-1,-1],'HorizontalAlignment','left','ListboxTop',[],'Max',[1],'Min',[0],'Position',[0,0,1,1],'Relief','default','SliderStep',[0.01,0.1],'String','Engineering Simulation Studio','Style','frame','Value',[0],'VerticalAlignment','middle','Visible','on','Tag','mainFigure','Callback','')
handles.lblMainTitle=uicontrol(f,'unit','normalized','BackgroundColor',[0.96,0.96,0.96],'Enable','on','FontAngle','normal','FontName','Tahoma','FontSize',[20],'FontUnits','points','FontWeight','bold','ForegroundColor',[0.08,0.08,0.08],'HorizontalAlignment','center','ListboxTop',[],'Max',[1],'Min',[0],'Position',[0.3,0.915,0.4,0.035],'Relief','default','SliderStep',[0.01,0.1],'String','ENGINEERING SIMULATION STUDIO','Style','text','Value',[0],'VerticalAlignment','middle','Visible','on','Tag','lblMainTitle','Callback','')
handles.lblSubtitle=uicontrol(f,'unit','normalized','BackgroundColor',[0.96,0.96,0.96],'Enable','on','FontAngle','normal','FontName','Tahoma','FontSize',[10],'FontUnits','points','FontWeight','normal','ForegroundColor',[0.35,0.35,0.35],'HorizontalAlignment','center','ListboxTop',[],'Max',[1],'Min',[0],'Position',[0.3,0.865,0.4,0.025],'Relief','default','SliderStep',[0.01,0.1],'String','Interactive Scientific & Engineering Sandbox','Style','text','Value',[0],'VerticalAlignment','middle','Visible','on','Tag','lblSubtitle','Callback','')
handles.panelLeft=uicontrol(f,'unit','normalized','BackgroundColor',[0.94,0.94,0.94],'Enable','on','FontAngle','normal','FontName','Tahoma','FontSize',[12],'FontUnits','points','FontWeight','normal','ForegroundColor',[-1,-1,-1],'HorizontalAlignment','left','ListboxTop',[],'Max',[1],'Min',[0],'Position',[0.0085,0.2734,0.1999,0.6123],'Relief','default','SliderStep',[0.01,0.1],'String','UnName4','Style','frame','Value',[0],'VerticalAlignment','middle','Visible','on','Tag','panelLeft','Callback','')
handles.panelCenter=uicontrol(f,'unit','normalized','BackgroundColor',[0.985,0.985,0.985],'Enable','on','FontAngle','normal','FontName','Tahoma','FontSize',[12],'FontUnits','points','FontWeight','normal','ForegroundColor',[-1,-1,-1],'HorizontalAlignment','left','ListboxTop',[],'Max',[1],'Min',[0],'Position',[0.2148,0.2734,0.4863,0.6123],'Relief','default','SliderStep',[0.01,0.1],'String','UnName5','Style','frame','Value',[0],'VerticalAlignment','middle','Visible','on','Tag','panelCenter','Callback','')
handles.panelRight=uicontrol(f,'unit','normalized','BackgroundColor',[0.94,0.94,0.94],'Enable','on','FontAngle','normal','FontName','Tahoma','FontSize',[12],'FontUnits','points','FontWeight','normal','ForegroundColor',[-1,-1,-1],'HorizontalAlignment','left','ListboxTop',[],'Max',[1],'Min',[0],'Position',[0.7096,0.2734,0.2702,0.6123],'Relief','default','SliderStep',[0.01,0.1],'String','UnName6','Style','frame','Value',[0],'VerticalAlignment','middle','Visible','on','Tag','panelRight','Callback','')
handles.panelResults=uicontrol(f,'unit','normalized','BackgroundColor',[0.94,0.94,0.94],'Enable','on','FontAngle','normal','FontName','Tahoma','FontSize',[12],'FontUnits','points','FontWeight','normal','ForegroundColor',[-1,-1,-1],'HorizontalAlignment','left','ListboxTop',[],'Max',[1],'Min',[0],'Position',[0.0085,0.0303,0.972,0.2305],'Relief','default','SliderStep',[0.01,0.1],'String','UnName7','Style','frame','Value',[0],'VerticalAlignment','middle','Visible','on','Tag','panelResults','Callback','')
handles.lblFundamental=uicontrol(f,'unit','normalized','BackgroundColor',[0.94,0.94,0.94],'Enable','on','FontAngle','normal','FontName','Tahoma','FontSize',[13],'FontUnits','points','FontWeight','bold','ForegroundColor',[-1,-1,-1],'HorizontalAlignment','left','ListboxTop',[],'Max',[1],'Min',[0],'Position',[0.0241,0.8486,0.1628,0.0244],'Relief','default','SliderStep',[0.01,0.1],'String','FUNDAMENTAL PHYSICS','Style','text','Value',[0],'VerticalAlignment','middle','Visible','on','Tag','lblFundamental','Callback','')
handles.popupBasic=uicontrol(f,'unit','normalized','BackgroundColor',[1,1,1],'Enable','on','FontAngle','normal','FontName','Tahoma','FontSize',[12],'FontUnits','points','FontWeight','normal','ForegroundColor',[0.08,0.08,0.08],'HorizontalAlignment','left','ListboxTop',[],'Max',[1],'Min',[0],'Position',[0.0241,0.7959,0.168,0.0391],'Relief','default','SliderStep',[0.01,0.1],'String','Pendulum|Projectile Motion','Style','popupmenu','Value',[1],'VerticalAlignment','middle','Visible','on','Tag','popupBasic','Callback','popupBasic_callback(handles)')
handles.lblNavigationInfo=uicontrol(f,'unit','normalized','BackgroundColor',[0.94,0.94,0.94],'Enable','on','FontAngle','normal','FontName','Tahoma','FontSize',[9],'FontUnits','points','FontWeight','normal','ForegroundColor',[0.35,0.35,0.35],'HorizontalAlignment','left','ListboxTop',[],'Max',[1],'Min',[0],'Position',[0.0241,0.5225,0.1562,0.0439],'Relief','default','SliderStep',[0.01,0.1],'String','Select a simulation from the above menus to begin.','Style','text','Value',[0],'VerticalAlignment','middle','Visible','on','Tag','lblNavigationInfo','Callback','')
handles.lblSimulationTitle=uicontrol(f,'unit','normalized','BackgroundColor',[-1,-1,-1],'Enable','on','FontAngle','normal','FontName','Tahoma','FontSize',[15],'FontUnits','points','FontWeight','bold','ForegroundColor',[0.08,0.08,0.08],'HorizontalAlignment','center','ListboxTop',[],'Max',[1],'Min',[0],'Position',[0.2148,0.8457,0.4863,0.04],'Relief','default','SliderStep',[0.01,0.1],'String','SIMULATION','Style','text','Value',[0],'VerticalAlignment','middle','Visible','on','Tag','lblSimulationTitle','Callback','')
handles.simulationArea=uicontrol(f,'unit','normalized','BackgroundColor',[1,1,1],'Enable','on','FontAngle','normal','FontName','Tahoma','FontSize',[12],'FontUnits','points','FontWeight','normal','ForegroundColor',[-1,-1,-1],'HorizontalAlignment','left','ListboxTop',[],'Max',[1],'Min',[0],'Position',[0.2305,0.5098,0.4538,0.3184],'Relief','default','SliderStep',[0.01,0.1],'String','UnName12','Style','frame','Value',[0],'VerticalAlignment','middle','Visible','on','Tag','simulationArea','Callback','')
handles.lblStatus=uicontrol(f,'unit','normalized','BackgroundColor',[0.98,0.98,0.98],'Enable','on','FontAngle','normal','FontName','Tahoma','FontSize',[10],'FontUnits','points','FontWeight','normal','ForegroundColor',[0.25,0.25,0.25],'HorizontalAlignment','center','ListboxTop',[],'Max',[1],'Min',[0],'Position',[0.2305,0.4541,0.4538,0.0391],'Relief','default','SliderStep',[0.01,0.1],'String','Ready - Select a simulation and press START','Style','text','Value',[0],'VerticalAlignment','middle','Visible','on','Tag','lblStatus','Callback','')
handles.lblParameters=uicontrol(f,'unit','normalized','BackgroundColor',[0.94,0.94,0.94],'Enable','on','FontAngle','normal','FontName','Tahoma','FontSize',[13],'FontUnits','points','FontWeight','bold','ForegroundColor',[0.08,0.08,0.08],'HorizontalAlignment','left','ListboxTop',[],'Max',[1],'Min',[0],'Position',[0.2148,0.4111,0.4863,0.0312],'Relief','default','SliderStep',[0.01,0.1],'String',' PARAMETERS ','Style','text','Value',[0],'VerticalAlignment','middle','Visible','on','Tag','lblParameters','Callback','')
handles.lblParam1=uicontrol(f,'unit','normalized','BackgroundColor',[0.985,0.985,0.985],'Enable','on','FontAngle','normal','FontName','Tahoma','FontSize',[10],'FontUnits','points','FontWeight','normal','ForegroundColor',[0.08,0.08,0.08],'HorizontalAlignment','left','ListboxTop',[],'Max',[1],'Min',[0],'Position',[0.275,0.373,0.1224,0.0244],'Relief','default','SliderStep',[0.01,0.1],'String','Parameter 1','Style','text','Value',[0],'VerticalAlignment','middle','Visible','on','Tag','lblParam1','Callback','')
handles.lblParam2=uicontrol(f,'unit','normalized','BackgroundColor',[0.985,0.985,0.985],'Enable','on','FontAngle','normal','FontName','Tahoma','FontSize',[10],'FontUnits','points','FontWeight','normal','ForegroundColor',[0.08,0.08,0.08],'HorizontalAlignment','left','ListboxTop',[],'Max',[1],'Min',[0],'Position',[0.4443,0.373,0.1198,0.0244],'Relief','default','SliderStep',[0.01,0.1],'String','Parameter 2','Style','text','Value',[0],'VerticalAlignment','middle','Visible','on','Tag','lblParam2','Callback','')
handles.lblParam3=uicontrol(f,'unit','normalized','BackgroundColor',[0.985,0.985,0.985],'Enable','on','FontAngle','normal','FontName','Tahoma','FontSize',[10],'FontUnits','points','FontWeight','normal','ForegroundColor',[0.08,0.08,0.08],'HorizontalAlignment','left','ListboxTop',[],'Max',[1],'Min',[0],'Position',[0.6142,0.373,0.0833,0.0244],'Relief','default','SliderStep',[0.01,0.1],'String','Parameter 3','Style','text','Value',[0],'VerticalAlignment','middle','Visible','on','Tag','lblParam3','Callback','')
handles.sliderParam1=uicontrol(f,'unit','normalized','BackgroundColor',[0.94,0.94,0.94],'Enable','on','FontAngle','normal','FontName','Tahoma','FontSize',[12],'FontUnits','points','FontWeight','normal','ForegroundColor',[-1,-1,-1],'HorizontalAlignment','left','ListboxTop',[],'Max',[100],'Min',[0],'Position',[0.235,0.3425,0.1224,0.0195],'Relief','default','SliderStep',[1,10],'String','UnName18','Style','slider','Value',[50],'VerticalAlignment','middle','Visible','on','Tag','sliderParam1','Callback','sliderParam1_callback(handles)')
handles.sliderParam2=uicontrol(f,'unit','normalized','BackgroundColor',[-1,-1,-1],'Enable','on','FontAngle','normal','FontName','Tahoma','FontSize',[12],'FontUnits','points','FontWeight','normal','ForegroundColor',[-1,-1,-1],'HorizontalAlignment','left','ListboxTop',[],'Max',[100],'Min',[0],'Position',[0.4043,0.3425,0.1198,0.0195],'Relief','default','SliderStep',[1,10],'String','UnName19','Style','slider','Value',[50],'VerticalAlignment','middle','Visible','on','Tag','sliderParam2','Callback','sliderParam2_callback(handles)')
handles.sliderParam3=uicontrol(f,'unit','normalized','BackgroundColor',[-1,-1,-1],'Enable','on','FontAngle','normal','FontName','Tahoma','FontSize',[12],'FontUnits','points','FontWeight','normal','ForegroundColor',[-1,-1,-1],'HorizontalAlignment','left','ListboxTop',[],'Max',[100],'Min',[0],'Position',[0.5742,0.3425,0.1133,0.0195],'Relief','default','SliderStep',[1,10],'String','UnName20','Style','slider','Value',[50],'VerticalAlignment','middle','Visible','on','Tag','sliderParam3','Callback','sliderParam3_callback(handles)')
handles.btnStart=uicontrol(f,'unit','normalized','BackgroundColor',[1,1,1],'Enable','on','FontAngle','normal','FontName','Tahoma','FontSize',[10],'FontUnits','points','FontWeight','bold','ForegroundColor',[-1,-1,-1],'HorizontalAlignment','center','ListboxTop',[],'Max',[1],'Min',[0],'Position',[0.235,0.293,0.1198,0.0352],'Relief','default','SliderStep',[0.01,0.1],'String','START','Style','pushbutton','Value',[0],'VerticalAlignment','middle','Visible','on','Tag','btnStart','Callback','btnStart_callback(handles)')
handles.btnReset=uicontrol(f,'unit','normalized','BackgroundColor',[1,1,1],'Enable','on','FontAngle','normal','FontName','Tahoma','FontSize',[10],'FontUnits','points','FontWeight','normal','ForegroundColor',[0.08,0.08,0.08],'HorizontalAlignment','center','ListboxTop',[],'Max',[1],'Min',[0],'Position',[0.5684,0.293,0.1198,0.0352],'Relief','default','SliderStep',[0.01,0.1],'String','RESET ','Style','pushbutton','Value',[0],'VerticalAlignment','middle','Visible','on','Tag','btnReset','Callback','btnReset_callback(handles)')
handles.lblGraphs=uicontrol(f,'unit','normalized','BackgroundColor',[0.94,0.94,0.94],'Enable','on','FontAngle','normal','FontName','Tahoma','FontSize',[15],'FontUnits','points','FontWeight','bold','ForegroundColor',[0.08,0.08,0.08],'HorizontalAlignment','center','ListboxTop',[],'Max',[1],'Min',[0],'Position',[0.7096,0.8486,0.2702,0.0244],'Relief','default','SliderStep',[0.01,0.1],'String','LIVE GRAPHS','Style','text','Value',[0],'VerticalAlignment','middle','Visible','on','Tag','lblGraphs','Callback','')
handles.graphArea1=uicontrol(f,'unit','normalized','BackgroundColor',[1,1,1],'Enable','on','FontAngle','normal','FontName','Tahoma','FontSize',[12],'FontUnits','points','FontWeight','normal','ForegroundColor',[-1,-1,-1],'HorizontalAlignment','left','ListboxTop',[],'Max',[1],'Min',[0],'Position',[0.7188,0.6738,0.252,0.1543],'Relief','groove','SliderStep',[0.01,0.1],'String','UnName24','Style','frame','Value',[0],'VerticalAlignment','middle','Visible','on','Tag','graphArea1','Callback','')
handles.lblGraph1=uicontrol(f,'unit','normalized','BackgroundColor',[1,1,1],'Enable','on','FontAngle','normal','FontName','Tahoma','FontSize',[10],'FontUnits','points','FontWeight','normal','ForegroundColor',[0.35,0.35,0.35],'HorizontalAlignment','center','ListboxTop',[],'Max',[1],'Min',[0],'Position',[0.735,0.735,0.2,0.025],'Relief','default','SliderStep',[0.01,0.1],'String','GRAPH 1','Style','text','Value',[0],'VerticalAlignment','middle','Visible','on','Tag','lblGraph1','Callback','')
handles.graphArea2=uicontrol(f,'unit','normalized','BackgroundColor',[1,1,1],'Enable','on','FontAngle','normal','FontName','Tahoma','FontSize',[12],'FontUnits','points','FontWeight','normal','ForegroundColor',[-1,-1,-1],'HorizontalAlignment','left','ListboxTop',[],'Max',[1],'Min',[0],'Position',[0.7188,0.502,0.252,0.1543],'Relief','groove','SliderStep',[0.01,0.1],'String','UnName26','Style','frame','Value',[0],'VerticalAlignment','middle','Visible','on','Tag','graphArea2','Callback','')
handles.lblGraph2=uicontrol(f,'unit','normalized','BackgroundColor',[1,1,1],'Enable','on','FontAngle','normal','FontName','Tahoma','FontSize',[10],'FontUnits','points','FontWeight','normal','ForegroundColor',[0.35,0.35,0.35],'HorizontalAlignment','center','ListboxTop',[],'Max',[1],'Min',[0],'Position',[0.735,0.563,0.2,0.025],'Relief','default','SliderStep',[0.01,0.1],'String','GRAPH 2','Style','text','Value',[0],'VerticalAlignment','middle','Visible','on','Tag','lblGraph2','Callback','')
handles.graphArea3=uicontrol(f,'unit','normalized','BackgroundColor',[1,1,1],'Enable','on','FontAngle','normal','FontName','Tahoma','FontSize',[12],'FontUnits','points','FontWeight','normal','ForegroundColor',[-1,-1,-1],'HorizontalAlignment','left','ListboxTop',[],'Max',[1],'Min',[0],'Position',[0.7188,0.2861,0.252,0.1973],'Relief','groove','SliderStep',[0.01,0.1],'String','UnName28','Style','frame','Value',[0],'VerticalAlignment','middle','Visible','on','Tag','graphArea3','Callback','')
handles.lblGraph3=uicontrol(f,'unit','normalized','BackgroundColor',[1,1,1],'Enable','on','FontAngle','normal','FontName','Tahoma','FontSize',[10],'FontUnits','points','FontWeight','normal','ForegroundColor',[0.35,0.35,0.35],'HorizontalAlignment','center','ListboxTop',[],'Max',[1],'Min',[0],'Position',[0.735,0.365,0.2,0.025],'Relief','default','SliderStep',[0.01,0.1],'String','GRAPH 3','Style','text','Value',[0],'VerticalAlignment','middle','Visible','on','Tag','lblGraph3','Callback','')
handles.lblResults=uicontrol(f,'unit','normalized','BackgroundColor',[0.94,0.94,0.94],'Enable','on','FontAngle','normal','FontName','Tahoma','FontSize',[13],'FontUnits','points','FontWeight','bold','ForegroundColor',[0.08,0.08,0.08],'HorizontalAlignment','left','ListboxTop',[],'Max',[1],'Min',[0],'Position',[0.0247,0.2246,0.1562,0.0244],'Relief','default','SliderStep',[0.01,0.1],'String','SIMULATION RESULTS','Style','text','Value',[0],'VerticalAlignment','middle','Visible','on','Tag','lblResults','Callback','')
handles.tblResults=uicontrol(f,'unit','normalized','BackgroundColor',[1,1,1],'Enable','on','FontAngle','normal','FontName','Tahoma','FontSize',[9],'FontUnits','points','FontWeight','normal','ForegroundColor',[0.08,0.08,0.08],'HorizontalAlignment','left','ListboxTop',[],'Max',[1],'Min',[0],'Position',[0.1144,0.0403,0.7519,0.1543],'Relief','default','SliderStep',[0.01,0.1],'String','UnName31','Style','table','Value',[0],'VerticalAlignment','middle','Visible','on','Tag','tblResults','Callback','tblResults_callback(handles)')
handles.lblSimulationInfo=uicontrol(f,'unit','normalized','BackgroundColor',[0.94,0.94,0.94],'Enable','on','FontAngle','normal','FontName','Tahoma','FontSize',[10],'FontUnits','points','FontWeight','normal','ForegroundColor',[0.35,0.35,0.35],'HorizontalAlignment','right','ListboxTop',[],'Max',[1],'Min',[0],'Position',[0.7891,0.2138,0.1172,0.0244],'Relief','default','SliderStep',[0.01,0.1],'String','Simulation: None','Style','text','Value',[0],'VerticalAlignment','middle','Visible','on','Tag','lblSimulationInfo','Callback','')
handles.simulationArea=uicontrol(f,'unit','normalized','BackgroundColor',[1,1,1],'Enable','on','FontAngle','normal','FontName','Tahoma','FontSize',[12],'FontUnits','points','FontWeight','normal','ForegroundColor',[-1,-1,-1],'HorizontalAlignment','left','ListboxTop',[],'Max',[1],'Min',[0],'Position',[0.2305,0.5098,0.4538,0.3184],'Relief','groove','SliderStep',[0.01,0.1],'String','UnName33','Style','frame','Value',[0],'VerticalAlignment','middle','Visible','on','Tag','simulationArea','Callback','')
handles.lblStatus=uicontrol(f,'unit','normalized','BackgroundColor',[0.98,0.98,0.98],'Enable','on','FontAngle','normal','FontName','Tahoma','FontSize',[10],'FontUnits','points','FontWeight','normal','ForegroundColor',[-1,-1,-1],'HorizontalAlignment','center','ListboxTop',[],'Max',[1],'Min',[0],'Position',[0.2305,0.4541,0.4538,0.0391],'Relief','default','SliderStep',[0.01,0.1],'String','Ready - Select a simulation and press START','Style','text','Value',[0],'VerticalAlignment','middle','Visible','on','Tag','lblStatus','Callback','')

f.visible = "on";

//////////
// Callbacks are defined as below. Please do not delete the comments as it will be used in coming version
//////////

function popupBasic_callback(handles)
//Write your callback for  popupBasic  here

    choice = get(handles.popupBasic, "Value");

    // ==========================================
    // 1. PENDULUM
    // ==========================================
    if choice == 1 then

        set(handles.lblParam1, "String", "Length (m)");
        set(handles.lblParam2, "String", "Mass (kg)");
        set(handles.lblParam3, "String", "Angle (deg)");

        set(handles.sliderParam1, "Min", 0.5);
        set(handles.sliderParam1, "Max", 5);
        set(handles.sliderParam1, "Value", 1);

        set(handles.sliderParam2, "Min", 0.1);
        set(handles.sliderParam2, "Max", 10);
        set(handles.sliderParam2, "Value", 1);

        set(handles.sliderParam3, "Min", 0);
        set(handles.sliderParam3, "Max", 90);
        set(handles.sliderParam3, "Value", 30);

        set(handles.lblStatus, "String", ...
        "Ready - Pendulum simulation");

        set(handles.lblSimulationInfo, "String", ...
        "Simulation: Pendulum");

    // ==========================================
    // 2. PROJECTILE MOTION
    // ==========================================
    elseif choice == 2 then

        set(handles.lblParam1, "String", "Velocity (m/s)");
        set(handles.lblParam2, "String", "Angle (deg)");
        set(handles.lblParam3, "String", "Gravity (m/s^2)");

        set(handles.sliderParam1, "Min", 1);
        set(handles.sliderParam1, "Max", 100);
        set(handles.sliderParam1, "Value", 20);

        set(handles.sliderParam2, "Min", 0);
        set(handles.sliderParam2, "Max", 90);
        set(handles.sliderParam2, "Value", 45);

        set(handles.sliderParam3, "Min", 1);
        set(handles.sliderParam3, "Max", 20);
        set(handles.sliderParam3, "Value", 9.81);

        set(handles.lblStatus, "String", ...
        "Ready - Projectile Motion");

        set(handles.lblSimulationInfo, "String", ...
        "Simulation: Projectile Motion");

    end

endfunction

function popupEngineering_callback(handles)
//Write your callback for  popupEngineering  here

endfunction

function sliderParam1_callback(handles)
//Write your callback for  sliderParam1  here

    choice = get(handles.popupBasic, "Value");

    if choice == 1 then

        value = get(handles.sliderParam1, "Value");

        set(handles.lblParam1, "String", ...
        msprintf("Length (m): %.2f", value));

        updatePendulumResults(handles);
        updatePendulumGraph(handles);
        updatePendulumGraph2(handles);
        updatePendulumGraph3(handles);

    elseif choice == 2 then

        value = get(handles.sliderParam1, "Value");

        set(handles.lblParam1, "String", ...
        msprintf("Velocity (m/s): %.2f", value));

        updateProjectileResults(handles);
        updateProjectileGraph1(handles);
        updateProjectileGraph2(handles);
        updateProjectileGraph3(handles);

    end

endfunction

function sliderParam2_callback(handles)
//Write your callback for  sliderParam2  here

    choice = get(handles.popupBasic, "Value");

    if choice == 1 then

        value = get(handles.sliderParam2, "Value");

        set(handles.lblParam2, "String", ...
        msprintf("Mass (kg): %.2f", value));

        updatePendulumResults(handles);
        updatePendulumGraph3(handles);

    elseif choice == 2 then

        value = get(handles.sliderParam2, "Value");

        set(handles.lblParam2, "String", ...
        msprintf("Angle (deg): %.2f", value));

        updateProjectileResults(handles);
        updateProjectileGraph1(handles);
        updateProjectileGraph2(handles);
        updateProjectileGraph3(handles);

    end

endfunction

function sliderParam3_callback(handles)
//Write your callback for  sliderParam3  here

    choice = get(handles.popupBasic, "Value");

    if choice == 1 then

        value = get(handles.sliderParam3, "Value");

        set(handles.lblParam3, "String", ...
        msprintf("Angle (deg): %.2f", value));

        updatePendulumResults(handles);
        updatePendulumGraph(handles);
        updatePendulumGraph2(handles);
        updatePendulumGraph3(handles);

    elseif choice == 2 then

        value = get(handles.sliderParam3, "Value");

        set(handles.lblParam3, "String", ...
        msprintf("Gravity (m/s^2): %.2f", value));

        updateProjectileResults(handles);
        updateProjectileGraph1(handles);
        updateProjectileGraph2(handles);
        updateProjectileGraph3(handles);

    end

endfunction

function btnStart_callback(handles)
//Write your callback for  btnStart  here

    choice = get(handles.popupBasic, "Value");
    
    // ==========================================
    // PROJECTILE MOTION
    // ==========================================
    
    if choice == 2 then
    
        runProjectileSimulation(handles);
    
        updateProjectileResults(handles);
    
        updateProjectileGraph1(handles);
    
        updateProjectileGraph2(handles);
    
        updateProjectileGraph3(handles);
    
        return;
    
    end
    
    
    // ==========================================
    // PENDULUM
    // ==========================================
    
    if choice <> 1 then
    
        set(handles.lblStatus, "String", ...
        "Select Pendulum or Projectile Motion");
    
        return;
    
    end

    L = get(handles.sliderParam1, "Value");
    M = get(handles.sliderParam2, "Value");
    theta0_deg = get(handles.sliderParam3, "Value");

    theta0 = theta0_deg * %pi / 180;

    g = 9.81;

    frame = handles.simulationArea;

    children = frame.children;

    if size(children, "*") > 0 then
        delete(children);
    end

    ax = newaxes(frame);

    // Hide GRAPH 1 label
    h = findobj("String", "GRAPH 1");

    if size(h, "*") > 0 then
        set(h, "Visible", "off");
    end

    ax.data_bounds = [-1.2*L, -1.2*L; 1.2*L, 0.2*L];
    ax.axes_visible = ["off","off","off"];

    theta = theta0;

    x = L * sin(theta);
    y = -L * cos(theta);

    rod = plot(ax, [0 x], [0 y]);

    bob = plot(ax, x, y, "o");

    bob.mark_size = 14;

    set(handles.lblStatus, "String", ...
    "Running - Pendulum simulation");

    t = 0;
    dt = 0.03;

    while t <= 10

        theta = theta0 * cos(sqrt(g/L) * t);

        x = L * sin(theta);
        y = -L * cos(theta);

        rod.data = [0 0; x y];

        bob.data = [x y];

        drawnow();

        sleep(30);

        t = t + dt;

    end

    set(handles.lblStatus, "String", ...
    "Simulation complete - Press START to run again");

    // Update graphs
    updatePendulumGraph(handles);
    updatePendulumGraph2(handles);
    updatePendulumGraph3(handles);

endfunction

function btnReset_callback(handles)
//Write your callback for  btnReset  here

    choice = get(handles.popupBasic, "Value");

    if choice == 1 then

        updatePendulumResults(handles);
        updatePendulumGraph(handles);
        updatePendulumGraph2(handles);
        updatePendulumGraph3(handles);
        set(handles.lblStatus, "String", "Ready - Pendulum simulation");

    elseif choice == 2 then

        updateProjectileResults(handles);
        updateProjectileGraph1(handles);
        updateProjectileGraph2(handles);
        updateProjectileGraph3(handles);
        set(handles.lblStatus, "String", "Ready - Projectile Motion");

    end

endfunction

function tblResults_callback(handles)
//Write your callback for  tblResults  here

endfunction

function pendulumTimerFcn(timerObj, event)

    // Get the main figure
    fig = gcf();

    // Check whether simulation is still running
    running = getappdata(fig, "simulationRunning");

    if ~running then
        stop(timerObj);
        delete(timerObj);
        return;
    end

    // Check pause state
    paused = getappdata(fig, "simulationPaused");

    if paused then
        return;
    end

    // Get stored objects
    rod = getappdata(fig, "pendulumRod");
    bob = getappdata(fig, "pendulumBob");

    // Get parameters
    L = getappdata(fig, "pendulumLength");
    theta0 = getappdata(fig, "pendulumAngle");
    g = getappdata(fig, "pendulumGravity");

    // Current time
    t = getappdata(fig, "simulationTime");

    // Pendulum equation
    theta = theta0 * cos(sqrt(g/L) * t);

    // Bob position
    x = L * sin(theta);
    y = -L * cos(theta);

    // Update rod
    rod.data = [0 0; x y];

    // Update bob
    bob.data = [x y];

    // Update time
    setappdata(fig, "simulationTime", t + 0.03);

    drawnow();

endfunction

function updatePendulumResults(handles)

    // Get current parameters

    L = get(handles.sliderParam1, "Value");

    M = get(handles.sliderParam2, "Value");

    theta0_deg = get(handles.sliderParam3, "Value");

    // Gravity

    g = 9.81;

    // Convert angle to radians

    theta0 = theta0_deg * %pi / 180;

    // Calculate period

    period = 2 * %pi * sqrt(L / g);

    // Calculate frequency

    frequency = 1 / period;

    // Calculate maximum velocity

    maxVelocity = sqrt(2 * g * L * (1 - cos(theta0)));

    // Create table

    results = [
        " "              "Value"                       "Unit";
        "Length"         msprintf("%.2f", L)           "m";
        "Mass"           msprintf("%.2f", M)           "kg";
        "Initial Angle"  msprintf("%.2f", theta0_deg)  "deg";
        "Period"         msprintf("%.2f", period)      "s";
        "Frequency"      msprintf("%.2f", frequency)   "Hz";
        "Max Velocity"   msprintf("%.2f", maxVelocity) "m/s"
    ];

    // Update table

    set(handles.tblResults, "String", results);

endfunction

function updatePendulumGraph(handles)

    // ==========================================
    // GET PENDULUM PARAMETERS
    // ==========================================

    L = get(handles.sliderParam1, "Value");

    theta0_deg = get(handles.sliderParam3, "Value");

    theta0 = theta0_deg * %pi / 180;

    g = 9.81;

    // ==========================================
    // TIME
    // ==========================================

    t = 0:0.02:10;

    // ==========================================
    // ANGLE
    // ==========================================

    theta = theta0 * cos(sqrt(g/L) * t);

    theta_deg = theta * 180 / %pi;

    // ==========================================
    // CLEAR OLD GRAPH
    // ==========================================

    frame = handles.graphArea1;

    children = frame.children;

    if size(children, "*") > 0 then
        delete(children);
    end

    // ==========================================
    // CREATE AXES
    // ==========================================

   ax = newaxes(frame);
   // Hide GRAPH 1 label
    h = findobj("String", "GRAPH 1");

    if size(h, "*") > 0 then
    set(h, "Visible", "off");
    end

    set(frame, "String", "");

    ax.data_bounds = [0, -theta0_deg*1.2;
                     10, theta0_deg*1.2];

    // ==========================================
    // PLOT
    // ==========================================

    plot(ax, t, theta_deg);

    // ==========================================
    // LABELS
    // ==========================================

    ax.x_label.text = "Time (s)";

    ax.y_label.text = "Angle (deg)";

    ax.title.text = "Pendulum Angle vs Time";

    ax.grid = [1 1];

endfunction

function updatePendulumGraph2(handles)

    // ==========================================
    // GET PARAMETERS
    // ==========================================

    L = get(handles.sliderParam1, "Value");

    theta0_deg = get(handles.sliderParam3, "Value");

    theta0 = theta0_deg * %pi / 180;

    g = 9.81;

    // ==========================================
    // TIME
    // ==========================================

    t = 0:0.02:10;

    // ==========================================
    // ANGULAR FREQUENCY
    // ==========================================

    omega = sqrt(g / L);

    // ==========================================
    // VELOCITY
    // ==========================================

    v = -L * theta0 * omega * sin(omega * t);

    // ==========================================
    // CLEAR OLD GRAPH
    // ==========================================

    frame = handles.graphArea2;

    children = frame.children;

    if size(children, "*") > 0 then
        delete(children);
    end

    // ==========================================
    // CREATE AXES
    // ==========================================

    ax = newaxes(frame);

    // Hide GRAPH 2 label
    h = findobj("String", "GRAPH 2");

    if size(h, "*") > 0 then
        set(h, "Visible", "off");
    end

    // ==========================================
    // GRAPH LIMITS
    // ==========================================

    vmax = max(abs(v));

    if vmax == 0 then
        vmax = 1;
    end

    ax.data_bounds = [0, -vmax*1.2;
                      10,  vmax*1.2];

    // ==========================================
    // PLOT
    // ==========================================

    plot(ax, t, v);

    // ==========================================
    // LABELS
    // ==========================================

    ax.x_label.text = "Time (s)";

    ax.y_label.text = "Velocity (m/s)";

    ax.title.text = "Pendulum Velocity vs Time";

    ax.grid = [1 1];

endfunction

function updatePendulumGraph3(handles)

    // ==========================================
    // GET PARAMETERS
    // ==========================================

    L = get(handles.sliderParam1, "Value");

    M = get(handles.sliderParam2, "Value");

    theta0_deg = get(handles.sliderParam3, "Value");

    theta0 = theta0_deg * %pi / 180;

    g = 9.81;

    // ==========================================
    // TIME
    // ==========================================

    t = 0:0.02:10;

    // ==========================================
    // ANGLE
    // ==========================================

    omega = sqrt(g / L);

    theta = theta0 * cos(omega * t);

    // ==========================================
    // VELOCITY
    // ==========================================

    v = -L * theta0 * omega * sin(omega * t);

    // ==========================================
    // KINETIC ENERGY
    // ==========================================

    KE = 0.5 * M .* v.^2;

    // ==========================================
    // POTENTIAL ENERGY
    // ==========================================

    PE = M * g * L .* (1 - cos(theta));

    // ==========================================
    // TOTAL ENERGY
    // ==========================================

    E = KE + PE;

    // ==========================================
    // CLEAR OLD GRAPH
    // ==========================================

    frame = handles.graphArea3;

    children = frame.children;

    if size(children, "*") > 0 then
        delete(children);
    end

    // ==========================================
    // CREATE AXES
    // ==========================================

    ax = newaxes(frame);

    // Hide GRAPH 3 label
    h = findobj("String", "GRAPH 3");

    if size(h, "*") > 0 then
        set(h, "Visible", "off");
    end

    // ==========================================
    // GRAPH LIMITS
    // ==========================================

    Emax = max(E);

    if Emax == 0 then
        Emax = 1;
    end

    ax.data_bounds = [0, 0;
                      10, Emax*1.2];

    // ==========================================
    // PLOT TOTAL ENERGY
    // ==========================================

    plot(ax, t, E);

    // ==========================================
    // LABELS
    // ==========================================

    ax.x_label.text = "Time (s)";

    ax.y_label.text = "Energy (J)";

    ax.title.text = "Mechanical Energy vs Time";

    ax.grid = [1 1];

endfunction

function updateProjectileResults(handles)

    // Get projectile parameters
    v0 = get(handles.sliderParam1, "Value");
    angle_deg = get(handles.sliderParam2, "Value");
    g = get(handles.sliderParam3, "Value");

    // Convert angle to radians
    angle = angle_deg * %pi / 180;

    // Time of flight
    timeFlight = (2 * v0 * sin(angle)) / g;

    // Maximum height
    maxHeight = (v0^2 * sin(angle)^2) / (2 * g);

    // Horizontal range
    range = (v0^2 * sin(2 * angle)) / g;

    // Create results table
    results = [
        "Parameter"          "Value"                       "Unit";
        "Initial Velocity"   msprintf("%.2f", v0)         "m/s";
        "Launch Angle"       msprintf("%.2f", angle_deg)  "deg";
        "Gravity"            msprintf("%.2f", g)         "m/s^2";
        "Time of Flight"     msprintf("%.2f", timeFlight) "s";
        "Maximum Height"     msprintf("%.2f", maxHeight) "m";
        "Range"              msprintf("%.2f", range)     "m"
    ];

    // Display results
    set(handles.tblResults, "String", results);

endfunction

function runProjectileSimulation(handles)

    // ==========================================
    // GET PARAMETERS
    // ==========================================

    v0 = get(handles.sliderParam1, "Value");
    angle_deg = get(handles.sliderParam2, "Value");
    g = get(handles.sliderParam3, "Value");

    angle = angle_deg * %pi / 180;


    // ==========================================
    // CALCULATE MOTION
    // ==========================================

    flightTime = 2 * v0 * sin(angle) / g;

    range = (v0^2 * sin(2 * angle)) / g;

    maxHeight = (v0^2 * sin(angle)^2) / (2 * g);


    // ==========================================
    // PROTECT AGAINST EDGE CASES
    // ==========================================

    if flightTime < 0.1 then
        flightTime = 0.1;
    end

    if range < 1 then
        xLimit = 1;
    else
        xLimit = range;
    end

    if maxHeight < 1 then
        yLimit = 1;
    else
        yLimit = maxHeight;
    end


    // ==========================================
    // CLEAR SIMULATION AREA
    // ==========================================

    frame = handles.simulationArea;

    children = frame.children;

    if size(children, "*") > 0 then
        delete(children);
    end


    // ==========================================
    // CREATE AXES
    // ==========================================

    ax = newaxes(frame);

    ax.data_bounds = [
        0, -0.05*yLimit;
        xLimit*1.10, yLimit*1.20
    ];

    ax.axes_visible = ["off","off","off"];


    // ==========================================
    // GROUND
    // ==========================================

    ground = plot(ax, ...
        [0 xLimit*1.05], ...
        [0 0]);


    // ==========================================
    // PROJECTILE
    // ==========================================

    projectile = plot(ax, ...
        [0 0], ...
        [0 0], ...
        "o");

    projectile.mark_size = 14;


    // ==========================================
    // TRAJECTORY
    // ==========================================

    trajectory = plot(ax, ...
        [0 0], ...
        [0 0]);


    // ==========================================
    // STATUS
    // ==========================================

    set(handles.lblStatus, ...
        "String", ...
        "Running - Projectile simulation");


    drawnow();


    // ==========================================
    // ANIMATION SETTINGS
    // ==========================================

    numberOfFrames = 150;

    dt = flightTime / numberOfFrames;


    // ==========================================
    // TRAJECTORY DATA
    // ==========================================

    trajectoryX = zeros(1, numberOfFrames + 1);

    trajectoryY = zeros(1, numberOfFrames + 1);


    // ==========================================
    // ANIMATION LOOP
    // ==========================================

    for i = 1:numberOfFrames + 1

        t = (i - 1) * dt;


        // Calculate position

        x = v0 * cos(angle) * t;

        y = v0 * sin(angle) * t ...
            - 0.5 * g * t^2;


        // Prevent tiny negative values
        // caused by floating point rounding

        if y < 0 then
            y = 0;
        end


        // Store trajectory

        trajectoryX(i) = x;

        trajectoryY(i) = y;


        // Update projectile

        projectile.data = [x y];


        // Update trail

        trajectory.data = ...
            [trajectoryX(1:i)' trajectoryY(1:i)'];


        // Force graphics refresh

        drawnow();


        // Small delay

        sleep(20);

    end


    // ==========================================
    // EXACT LANDING POSITION
    // ==========================================

    landingX = v0 * cos(angle) * flightTime;

    projectile.data = [landingX 0];


    trajectoryX(numberOfFrames + 1) = landingX;

    trajectoryY(numberOfFrames + 1) = 0;

    trajectory.data = ...
        [trajectoryX' trajectoryY'];


    drawnow();


    // ==========================================
    // COMPLETE
    // ==========================================

    set(handles.lblStatus, ...
        "String", ...
        "Simulation complete - Press START to run again");

endfunction

function updateProjectileGraph1(handles)

    // Get parameters
    v0 = get(handles.sliderParam1, "Value");
    angle_deg = get(handles.sliderParam2, "Value");
    g = get(handles.sliderParam3, "Value");

    angle = angle_deg * %pi / 180;

    // Time of flight
    flightTime = 2 * v0 * sin(angle) / g;

    // Time values
    t = 0:0.02:flightTime;

    // Height
    y = v0 * sin(angle) .* t - 0.5 * g .* t.^2;

    // Graph frame
    frame = handles.graphArea1;

    // Remove previous axes
    children = frame.children;

    if size(children, "*") > 0 then
        delete(children);
    end

    // Create axes
    ax = newaxes(frame);

    // Hide GRAPH 1 label
    h = findobj("String", "GRAPH 1");

    if size(h, "*") > 0 then
        set(h, "Visible", "off");
    end

    // Graph limits
    ymax = max(y);

    if ymax <= 0 then
        ymax = 1;
    end

    ax.data_bounds = [
        0, 0;
        flightTime, ymax*1.2
    ];

    // Plot
    plot(ax, t, y);

    // Labels
    ax.x_label.text = "Time (s)";
    ax.y_label.text = "Height (m)";
    ax.title.text = "Projectile Height vs Time";

    ax.grid = [1 1];

endfunction

function updateProjectileGraph2(handles)

    // Get parameters
    v0 = get(handles.sliderParam1, "Value");
    angle_deg = get(handles.sliderParam2, "Value");
    g = get(handles.sliderParam3, "Value");

    angle = angle_deg * %pi / 180;

    // Time of flight
    flightTime = 2 * v0 * sin(angle) / g;

    // Time values
    t = 0:0.02:flightTime;

    // Horizontal distance
    x = v0 * cos(angle) .* t;

    // Graph frame
    frame = handles.graphArea2;

    // Remove previous graph
    children = frame.children;

    if size(children, "*") > 0 then
        delete(children);
    end

    // Create axes
    ax = newaxes(frame);

    // Hide GRAPH 2 label
    h = findobj("String", "GRAPH 2");

    if size(h, "*") > 0 then
        set(h, "Visible", "off");
    end

    // Graph limits
    xmax = max(x);

    if xmax <= 0 then
        xmax = 1;
    end

    ax.data_bounds = [
        0, 0;
        max(flightTime, 1), max(xmax*1.1, 1)
    ];

    // Plot
    plot(ax, t, x);

    // Labels
    ax.x_label.text = "Time (s)";
    ax.y_label.text = "Distance (m)";
    ax.title.text = "Horizontal Distance vs Time";

    ax.grid = [1 1];

endfunction

function updateProjectileGraph3(handles)

    v0 = get(handles.sliderParam1, "Value");
    angle_deg = get(handles.sliderParam2, "Value");
    g = get(handles.sliderParam3, "Value");

    angle = angle_deg * %pi / 180;
    range = (v0^2 * sin(2 * angle)) / g;
    xMax = max(range, 1);

    if abs(cos(angle)) < 1d-8 then
        x = 0:0.01:xMax;
        y = v0^2/(2*g) - (g*x.^2)/(2*v0^2);
        y(y < 0) = 0;
    else
        x = 0:0.05:max(range, 0.05);
        y = x * tan(angle) - ...
            (g * x.^2) / (2 * v0^2 * cos(angle)^2);
        y(y < 0) = 0;
    end

    frame = handles.graphArea3;
    children = frame.children;
    if size(children, "*") > 0 then
        delete(children);
    end

    ax = newaxes(frame);

    h = findobj("String", "GRAPH 3");
    if size(h, "*") > 0 then
        set(h, "Visible", "off");
    end

    ymax = max(y);
    if ymax <= 0 then
        ymax = 1;
    end

    ax.data_bounds = [0, 0; xMax*1.1, ymax*1.2];

    plot(ax, x, y);

    ax.x_label.text = "Distance (m)";
    ax.y_label.text = "Height (m)";
    ax.title.text = "Projectile Trajectory";
    ax.grid = [1 1];

endfunction
